### ISSUE TITLE
2 database into 1

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_datamodel#10]
Should we just have one postgres database?

Currently we have 
- PV database
- Forecast database

We want to add
- GSP yield data
- (Future) PV site level forecasts

Pros of 1
- less maintenance / less terraform code
- less duplication of PV and GSP metadata
- potentially less cost?

Cons:
- a single point of failure
- less modular

would be interested to hear your thoughts @flowirtz and @JackKelly

**Comment by peterdudfield** [comment]
One way around this would be to put GSP yield data in the Forecast database. Then we could keep 2 databases. 
The GSP data, is like the truth values to the Forecast, so it makes sense they are in there. Then all PV data we will keep separate

**Comment by JackKelly** [comment]
Would the GSP data and PV forecasts be in separate tables within the same database?

The reason I ask is because I assume the database records the "creation_time" and the "target_time" for each forecast? But the concept of "creation_time" doesn't apply to ground truth :slightly_smiling_face:

**Comment by peterdudfield** [comment]
Yea, they were defiantly be in separate tables. Decision is about if they are in the same database or not

**Comment by JackKelly** [comment]
Oh, yeah, in which case, I'd definitely lean towards having a single database! (so, like you say, it's really easy to query for the ground truth and the forecast in a single query)

**Comment by peterdudfield** [comment]
yea, and then the question is, does all the PV data get stored somewhere else? in a different database. My feeling was to keep it separate (seperate databases)

**Comment by JackKelly** [comment]
Yeah, I don't have any hugely strong opinions!

It might be nice to do things like "plot all the individual PV systems for a given GSP region; and the OCF PV forecasts for that GSP; and the PV Live for that GSP". Which might be a _tiny_ bit easier if everything was in a single database. But I guess it doesn't matter too much. And, like you say, it's probably good to keep things modular.

Sorry for the basic question but please remind me: are these databases Postgres SQL databases?

**Comment by peterdudfield** [comment]
yea all postgres, hosted in AWS RDS
