### ISSUE TITLE
Remove normalization warning

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_datamodel#115]
removing warning [here](https://github.com/openclimatefix/nowcasting_datamodel/blob/main/nowcasting_datamodel/models/forecast.py#L204), by just deleting the code

makes to much logging and is not useful

After merging, would be good to update api with the new datamodel version - https://github.com/openclimatefix/nowcasting_api

**Comment by lucasc896** [comment]
Tried to push to the repo but don't have write access. Am I expected to fork the repo and fix there?

**Comment by peterdudfield** [comment]
Hi @lucasc896 . Great you can want to do more. Could we try with you doing a PR first, then we can give you write access (once ive set up some branch protection)? I hope this isnt blocking you, and really appreciate that you want to help - thanks

**Comment by peterdudfield** [comment]
sorry @lucasc896, I went ahead and did it as I was trying to debug something and these statements were annoying me

**Comment by peterdudfield** [comment]
@lucasc896 , this one is still available if you want it

**Comment by lucasc896** [comment]
Sorry @peterdudfield - it's been a hectic end to the year! Thanks for your suggestion 👍

**Comment by peterdudfield** [comment]
no worries @lucasc896 , thanks very much for doing this.
