### ISSUE TITLE
reduce duplicate in tests

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_datamodel#226]
## Detailed Description
Currently there is lots of duplication in the [blend tests](https://github.com/openclimatefix/nowcasting_datamodel/blob/main/tests/read/blend/test_blend.py)

## Context
- always good to reduce code
- this code test blending different forecast together

## Possible Implementation
- make conftest.py or some functions to make fake data

**Comment by roshnaeem** [comment]
@peterdudfield , i think this PR will also close https://github.com/openclimatefix/nowcasting_datamodel/issues/226
