### ISSUE TITLE
remove blend

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_datamodel#248]
## Detailed Description
We moved the blend service to https://github.com/openclimatefix/uk-pv-forecast-blend and therefore can delete some stuff here

## Context
- blend service mixes together the 3 different forecasts in a safe way

## Possible Implementation
- remove read/blend folder + any relevant tests

**Comment by peterdudfield** [comment]
ALl the function in here can be removed - https://github.com/openclimatefix/nowcasting_datamodel/tree/main/nowcasting_datamodel/read/blend

**Comment by roshnaeem** [comment]
@peterdudfield, can I work on this one?

**Comment by peterdudfield** [comment]
@all-contributors please add @roshnaeem  for code
