### ISSUE TITLE
Upgrade to SQLAlchemy>2.0

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_datamodel#273]
## Detailed Description
Good to upgrade to SQLAlchemy

## Context
- similar to https://github.com/openclimatefix/pv-site-datamodel/issues/88

## Possible Implementation
upgrade requiremtns, upgrade code, run tests

**Comment by rahul-maurya11b** [comment]
@peterdudfield  sir I have solved a similar issue can you please assign me this issue also?

**Comment by rahul-maurya11b** [comment]
@peterdudfield  sir, please check #274 all tests are passing as before after changing the version of sqlalchemy to >2.0
