### ISSUE TITLE
pydantic: Upgrade validator to field_validator

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_datamodel#281]
Similar to https://github.com/openclimatefix/ocf_datapipes/issues/318

Upgrade current validators to field_validators

https://stackoverflow.com/questions/76734333/pydantic-v2-field-validator-values-argument-equivalent

**Comment by Bvr4** [comment]
Hello,
I might be interested in contributing to your project by taking charge of this issue. 
Can it be assigned to me?

**Comment by Plomo-02** [comment]
hello, can I be assigned to this issue?

**Comment by Bvr4** [comment]
Hello, while working on this issue, I read the pydantic migration guide and saw that the from_orm method is deprecated. I have seen this method in some models. Perhaps this could be the subject of a new issue?

**Comment by peterdudfield** [comment]
yes pelase, could you make a new issue for this? Thanks
