### ISSUE TITLE
Create datamodel for PV data

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_datamodel#4]
## Detailed Description
Create datamodel for pv data

metadata
- pv system id
- name?
- capacity?
- orientation?
- lattitude,
- longtitude
- provider: str

pv_yield:
- id
- datetime
- solar_generation_{units}
- pv system id

**Comment by JackKelly** [comment]
at the moment, none of our code makes use of capacity or orientation. But it might still be useful to store this data.

One quick question: How to distinguish between PV systems from PVOutput.org vs PassivSystems?

**Comment by peterdudfield** [comment]
> at the moment, none of our code makes use of capacity or orientation. But it might still be useful to store this data.
> 
> One quick question: How to distinguish between PV systems from PVOutput.org vs PassivSystems?

Yea, Capacity might be a good way to normalize things, rather than max value pv value of this historic data. 

Ill add a column for provider, then we know where is from

**Comment by JackKelly** [comment]
> Capacity might be a good way to normalize things, rather than max value pv value of this historic data

In my limited experience, the nominal capacity is often wrong. So, if we divide by the nominal capacity, we're very likely to get values above 1. I'd recommend that we continue normalising by the max of the timeseries :slightly_smiling_face:
